# Generated by Django 4.1.5 on 2023-01-23 09:37

import cloudinary.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Additionalloanpayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CapitalGrowthRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=8, null=True)),
                ('averagecapitalGrowthrate', models.FloatField(default=8, verbose_name='Average Capital Growth Rate (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Capitalincome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('rate', models.IntegerField(default=0, max_length=255, null=True, verbose_name='Rate (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Straight', 'Straight'), ('Diminishing', 'Diminishing')], default='Interest & capital', max_length=50, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('value', models.FloatField(null=True)),
                ('rate', models.IntegerField(default=8, max_length=255, null=True, verbose_name='Rate (%)')),
                ('years', models.IntegerField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InflationRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=8, max_length=255, null=True)),
                ('averageinflationrate', models.FloatField(default=8, null=True, verbose_name='Average Inflation Rate (%)')),
            ],
        ),
        migrations.CreateModel(
            name='InterestRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Interest & capital', 'Interest & capital'), ('Interest Only', 'Interest Only')], default='Interest & capital', max_length=50, null=True)),
                ('rate', models.IntegerField(default=10, max_length=255, null=True)),
                ('averageinterestrate', models.FloatField(default=10, null=True, verbose_name='Average Interest Rate (%)')),
                ('term', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRenovations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeperyear', models.FloatField(default=0, max_length=255, null=True, verbose_name='Income per year')),
                ('amount', models.IntegerField(default=0, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='managementexpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancyrate', models.IntegerField(default=0, max_length=255, null=True, verbose_name='Vacancy Rate (%)')),
                ('managementfee', models.IntegerField(default=0, max_length=255, null=True, verbose_name='Management Fee (%)')),
                ('managementfeeperyear', models.IntegerField(verbose_name='Management Fee per Year ')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('value', models.IntegerField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_costs', models.CharField(choices=[('Property Taxes', 'Property Taxes'), ('Repairs & Utilities', 'Repairs & Utilities'), ('Mortgage Insurance', 'Mortgage Insurance')], max_length=255, null=True)),
                ('amount', models.IntegerField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnRenovations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeperyear', models.FloatField(default=0, max_length=255, null=True, verbose_name='Income per year')),
                ('amount', models.IntegerField(default=0, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentalincreasetype', models.CharField(choices=[('capital', 'capital'), ('inflation', 'inflation'), ('percent', 'percent')], default='Interest & capital', max_length=50, null=True)),
                ('increasepercentage', models.IntegerField(max_length=255, verbose_name='Increase Percentage (%)')),
                ('averagerentalincomepermonth', models.FloatField(null=True, verbose_name='Average Rental Income Per Month')),
                ('amount', models.IntegerField(max_length=255, null=True, verbose_name='Amount')),
            ],
        ),
        migrations.CreateModel(
            name='repairs_maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='specialexpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='taxoptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxationcapacity', models.CharField(choices=[('Personal', 'Personal'), ('close corporation', 'close corporation'), ('private company', 'private company'), ('trust', 'trust')], default='Interest & capital', max_length=50, null=True)),
                ('method', models.CharField(choices=[('0%', '0%'), ('Marginal', 'Marginal'), ('Use Tax Table', 'Use Tax Table'), ('Custom', 'Custom')], default='Interest & capital', max_length=50, null=True)),
                ('taxrate', models.FloatField(null=True, verbose_name='Tax Rate(%)')),
                ('annualtaxableincome', models.FloatField(verbose_name='Annual Taxableincome(%)')),
                ('maximumtaxrate', models.IntegerField(max_length=255, verbose_name='Maximum Tax Rate (%)')),
                ('income', models.IntegerField(max_length=255, null=True)),
                ('rate', models.IntegerField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252, null=True)),
                ('purchase_date', models.DateField(auto_now_add=True, null=True)),
                ('purchase_price', models.FloatField(null=True)),
                ('deposit', models.FloatField(null=True)),
                ('bond_value', models.IntegerField(max_length=252, null=True)),
                ('notes', models.TextField(max_length=1260, null=True)),
                ('CapitalGrowthRates', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='investment.capitalgrowthrates')),
                ('Capitalincome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.capitalincome')),
                ('City', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.city')),
                ('InterestRates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.interestrates')),
                ('LoanRenovations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.loanrenovations')),
                ('MonthlyExpense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.monthlyexpense')),
                ('OwnRenovations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.ownrenovations')),
                ('RentalIncome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.rentalincome')),
                ('managementexpenses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.managementexpenses')),
                ('other_cost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.othercosts')),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.propertytype')),
                ('repairs_maintenance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.repairs_maintenance')),
                ('specialexpenses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.specialexpenses')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_pic', cloudinary.models.CloudinaryField(default='http://res.cloudinary.com/dim8pysls/image/upload/v1639001486/x3mgnqmbi73lten4ewzv.png', max_length=255, verbose_name='images')),
                ('bio', models.TextField(blank=True, default='please update your bio', max_length=255)),
                ('f_name', models.CharField(blank=True, max_length=255)),
                ('l_name', models.CharField(blank=True, max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='http://res.cloudinary.com/dim8pysls/image/upload/v1639001486/x3mgnqmbi73lten4ewzv.png', max_length=255, verbose_name='images')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.property')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.country'),
        ),
    ]
