# Generated by Django 4.1.5 on 2023-01-23 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='CapitalGrowthRates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.capitalgrowthrates'),
        ),
        migrations.AlterField(
            model_name='property',
            name='InterestRates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.interestrates'),
        ),
    ]
