# Generated by Django 4.1.5 on 2023-01-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalloanpayments',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='capitalincome',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='rate',
            field=models.IntegerField(default=0, null=True, verbose_name='Rate (%)'),
        ),
        migrations.AlterField(
            model_name='depreciation',
            name='rate',
            field=models.IntegerField(default=8, null=True, verbose_name='Rate (%)'),
        ),
        migrations.AlterField(
            model_name='depreciation',
            name='years',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inflationrates',
            name='rate',
            field=models.IntegerField(default=8, null=True),
        ),
        migrations.AlterField(
            model_name='interestrates',
            name='rate',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanrenovations',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanrenovations',
            name='incomeperyear',
            field=models.FloatField(default=0, null=True, verbose_name='Income per year'),
        ),
        migrations.AlterField(
            model_name='managementexpenses',
            name='managementfee',
            field=models.IntegerField(default=0, null=True, verbose_name='Management Fee (%)'),
        ),
        migrations.AlterField(
            model_name='managementexpenses',
            name='vacancyrate',
            field=models.IntegerField(default=0, null=True, verbose_name='Vacancy Rate (%)'),
        ),
        migrations.AlterField(
            model_name='monthlyexpense',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='othercosts',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ownrenovations',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ownrenovations',
            name='incomeperyear',
            field=models.FloatField(default=0, null=True, verbose_name='Income per year'),
        ),
        migrations.AlterField(
            model_name='rentalincome',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='rentalincome',
            name='increasepercentage',
            field=models.IntegerField(verbose_name='Increase Percentage (%)'),
        ),
        migrations.AlterField(
            model_name='repairs_maintenance',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='specialexpenses',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='taxoptions',
            name='income',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taxoptions',
            name='maximumtaxrate',
            field=models.IntegerField(verbose_name='Maximum Tax Rate (%)'),
        ),
        migrations.AlterField(
            model_name='taxoptions',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
