# Generated by Django 4.0.5 on 2023-01-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='location',
            new_name='City',
        ),
    ]
