# Generated by Django 4.1.5 on 2023-01-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflationrates',
            name='rate',
            field=models.FloatField(default=8, null=True),
        ),
        migrations.AlterField(
            model_name='interestrates',
            name='rate',
            field=models.FloatField(default=10, null=True),
        ),
    ]
