# Generated by Django 4.1.5 on 2023-01-31 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_alter_inflationrates_rate_alter_interestrates_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitalgrowthrates',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='loanrenovations',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ownrenovations',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ownrenovations',
            name='incomeperyear',
        ),
        migrations.RemoveField(
            model_name='rentalincome',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='repairs_maintenance',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='specialexpenses',
            name='amount',
        ),
    ]
