# Generated by Django 4.0.5 on 2023-01-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_rename_location_city_rename_location_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.country'),
        ),
    ]
