# Generated by Django 4.0.5 on 2023-01-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_property_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='property',
            name='other_cost',
        ),
    ]
