# Generated by Django 4.1.5 on 2023-02-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_remove_loanrenovations_incomeperyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestrates',
            name='rate',
        ),
    ]
