# Generated by Django 4.0.5 on 2023-01-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_remove_property_country_remove_property_other_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='other_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.othercosts'),
        ),
    ]
