# Generated by Django 4.0.5 on 2023-01-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0006_interestrates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestrates',
            name='rate',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
