# Generated by Django 4.0.5 on 2023-01-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_alter_interestrates_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestrates',
            name='type',
            field=models.CharField(choices=[('Interest & capital', 'Interest & capital'), ('Interest Only', 'Interest Only')], max_length=50, null=True),
        ),
    ]
