# Generated by Django 4.0.5 on 2023-01-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0008_interestrates_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestrates',
            name='property',
        ),
        migrations.RemoveField(
            model_name='interestrates',
            name='rate',
        ),
    ]
