# Generated by Django 4.0.5 on 2023-01-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0009_remove_interestrates_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestrates',
            name='averagerate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='interestrates',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.property'),
        ),
        migrations.AddField(
            model_name='interestrates',
            name='rate',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interestrates',
            name='term',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
