# Generated by Django 4.0.5 on 2023-01-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0010_interestrates_averagerate_interestrates_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestrates',
            name='averagerate',
            field=models.FloatField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='interestrates',
            name='rate',
            field=models.IntegerField(default=10, max_length=255, null=True),
        ),
    ]
