# Generated by Django 4.0.5 on 2023-01-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0011_alter_interestrates_averagerate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestrates',
            name='type',
            field=models.CharField(choices=[('Interest & capital', 'Interest & capital'), ('Interest Only', 'Interest Only')], default='Interest & capital', max_length=50, null=True),
        ),
    ]
