# Generated by Django 4.0.5 on 2023-01-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0012_alter_interestrates_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestrates',
            name='averagerate',
            field=models.FloatField(default=10, null=True, verbose_name='Average Rate'),
        ),
    ]
