# Generated by Django 4.1.5 on 2023-01-22 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0015_taxoptions_specialexpenses_repairs_maintenance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalloanpayments',
            name='property',
        ),
        migrations.RemoveField(
            model_name='capitalgrowthrates',
            name='property',
        ),
        migrations.RemoveField(
            model_name='capitalincome',
            name='property',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='property',
        ),
        migrations.RemoveField(
            model_name='depreciation',
            name='property',
        ),
        migrations.RemoveField(
            model_name='inflationrates',
            name='property',
        ),
        migrations.RemoveField(
            model_name='interestrates',
            name='property',
        ),
        migrations.RemoveField(
            model_name='loanrenovations',
            name='property',
        ),
        migrations.RemoveField(
            model_name='managementexpenses',
            name='property',
        ),
        migrations.RemoveField(
            model_name='monthlyexpense',
            name='property',
        ),
        migrations.RemoveField(
            model_name='ownrenovations',
            name='property',
        ),
        migrations.RemoveField(
            model_name='rentalincome',
            name='property',
        ),
        migrations.RemoveField(
            model_name='repairs_maintenance',
            name='property',
        ),
        migrations.RemoveField(
            model_name='specialexpenses',
            name='property',
        ),
        migrations.RemoveField(
            model_name='taxoptions',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='CapitalGrowthRates',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='investment.capitalgrowthrates'),
        ),
        migrations.AddField(
            model_name='property',
            name='Capitalincome',
            field=models.ForeignKey(default=0.0, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.capitalincome'),
        ),
        migrations.AddField(
            model_name='property',
            name='InterestRates',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='investment.interestrates'),
        ),
        migrations.AddField(
            model_name='property',
            name='LoanRenovations',
            field=models.ForeignKey(default=0.0, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.loanrenovations'),
        ),
        migrations.AddField(
            model_name='property',
            name='MonthlyExpense',
            field=models.ForeignKey(default=0.0, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.monthlyexpense'),
        ),
        migrations.AddField(
            model_name='property',
            name='OwnRenovations',
            field=models.ForeignKey(default=0.0, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.ownrenovations'),
        ),
        migrations.AddField(
            model_name='property',
            name='RentalIncome',
            field=models.ForeignKey(default=0.0, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.rentalincome'),
        ),
        migrations.AddField(
            model_name='property',
            name='managementexpenses',
            field=models.ForeignKey(default=0.0, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.managementexpenses'),
        ),
        migrations.AddField(
            model_name='property',
            name='repairs_maintenance',
            field=models.ForeignKey(default=0.0, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.repairs_maintenance'),
        ),
        migrations.AddField(
            model_name='property',
            name='specialexpenses',
            field=models.ForeignKey(default=0.0, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.specialexpenses'),
        ),
        migrations.AlterField(
            model_name='capitalgrowthrates',
            name='rate',
            field=models.IntegerField(default=8, null=True),
        ),
        migrations.AlterField(
            model_name='interestrates',
            name='term',
            field=models.IntegerField(null=True),
        ),
    ]
